# Generated by Django 4.1.5 on 2023-02-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_sensor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='sensor_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
